# Generated by Django 2.1 on 2018-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180819_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='path',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
